### ISSUE TITLE
给 purc 输出的 HTML 加一个 pretty printer 过滤

### ISSUE THREAD

**Issue by tiansiyuan** [HVML/PurC#13]
现在（Ubuntu 22.04.1 LTS）的输出是这样的：

tsy@tsy-Lenovo-V330-14IKB:~/PurC/build$ purc -b hvml/fibonacci-html-temp.hvml
purc 0.8.0
Copyright (C) 2022 FMSoft Technologies.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Executing HVML program from `file:///home/tsy/PurC/build/hvml/fibonacci-html-temp.hvml`...

The main coroutine exited.
>> The document generated:
<html>
  <head>
    <title>
      Fibonacci Numbers
    </title>
  </head>
  <body id="theBody">
    <h1>
      Fibonacci Numbers less than 2000
    </h1>
    <ol>
      <li>
        0
      </li>
      <li>
        1
      </li>
      <li>
        1
      </li>
      <li>
        2
      </li>
      <li>
        3
      </li>
      <li>
        5
      </li>
      <li>
        8
      </li>
      <li>
        13
      </li>
      <li>
        21
      </li>
      <li>
        34
      </li>
      <li>
        55
      </li>
      <li>
        89
      </li>
      <li>
        144
      </li>
      <li>
        233
      </li>
      <li>
        377
      </li>
      <li>
        610
      </li>
      <li>
        987
      </li>
      <li>
        1597
      </li>
    </ol>
    <p>
      Totally 
      18
       numbers
    </p>
  </body>
</html>

>> The executed result: 
[ 18, 1597 ]

经 pretty printer 过滤后的 HTML 部分看起来：

<html>
  <head>
    <title>Fibonacci Numbers</title>
  </head>
  <body id="theBody">
    <h1>Fibonacci Numbers less than 2000</h1>
    <ol>
      <li>0</li>
      <li>1</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>5</li>
      <li>8</li>
      <li>13</li>
      <li>21</li>
      <li>34</li>
      <li>55</li>
      <li>89</li>
      <li>144</li>
      <li>233</li>
      <li>377</li>
      <li>610</li>
      <li>987</li>
      <li>1597</li>
    </ol>
    <p>Totally 18 numbers</p>
  </body>
</html>

**Comment by tiansiyuan** [comment]
HTML 被 github 渲染了，请见附件：beforepp.txt 和 afterpp.txt。
[beforepp.txt](https://github.com/HVML/PurC/files/9265194/beforepp.txt)

[afterpp.txt](https://github.com/HVML/PurC/files/9265184/afterpp.txt)

**Comment by VincentWei** [comment]
Indeed, this is a bug. We will try to fix it in the next release.

**Comment by VincentWei** [comment]
This issue has been fixed and/or enhanced.
