### ISSUE TITLE
缺失共享库libpurc.so.0

### ISSUE THREAD

**Issue by shengliawa** [HVML/PurC#18]
![截图_滚动截图_20220818204455](https://user-images.githubusercontent.com/51014812/185397997-039de049-6710-4d4b-aa1a-177a9eef2e4d.png)

**Comment by VincentWei** [comment]
Make sure that you have added `/usr/local/lib` to `/etc/ld.so.conf` and run `sudo ldconfig` command,
in order that the system can find the shared library of PurC you just installed into `/usr/local/lib`.
