### ISSUE TITLE
路径包含中文导致的Bug Bug about the path which contains Chinese

### ISSUE THREAD

**Issue by longlongvip** [HVML/PurC#20]
## 如何复现 How to find
- 文件路径——file:///home/x/文档/HVML/hello.hvml
- File Path——file:///home/x/文档/HVML/hello.hvml
- 执行命令 Run Command——purc -b hello.hvml
- 执行结果 Run Results
```bash
purc 0.8.1
Copyright (C) 2022 FMSoft Technologies.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Failed to load HVML from file:///home/x/文档/HVML/hello.hvml: Bad system call
@localhost/cn.fmsoft.hvml.instmgr/main DEBUG >> InstMgr is quiting, 0 messages discarded
```
## 如何解决 How to solve
去掉中文 Remove Chinese
- 文件路径——file:///home/x/HVML/hello.hvml
- File Path——file:///home/x/HVML/hello.hvml
- 执行命令 Run Command——purc -b hello.hvml
- 执行结果 Run Results
```bash
purc 0.8.1
Copyright (C) 2022 FMSoft Technologies.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Executing HVML program from `file:///home/x/HVML/hello.hvml`...
Hello, world!

The main coroutine exited.
>> The document generated:

>> The executed result: 
14
@localhost/cn.fmsoft.hvml.instmgr/main DEBUG >> InstMgr is quiting, 0 messages discarded
```
## 问题
Purc不支持含有中文的路径 Purc does not support path which contains Chinese

**Comment by VincentWei** [comment]
Thank you very much!

This is the first bug reported by the community, and you give the very detailed information.
This will help the developer to fix the bug efficiently.

Thank you again!

**Comment by VincentWei** [comment]
This bug has been fixed.
