### ISSUE TITLE
<observe on $TIMERS for 'expired:foobar' >

### ISSUE THREAD

**Issue by goog** [HVML/PurC#29]
i hope the statement is simple like <code>observe 'some event' on timer_id</code> to make the expression more natural

**Comment by VincentWei** [comment]
It sounds reasonable, but we use `observe` not only for the expired event of a timer but also other events from various event source. For example, the event from the renderer indicating the user had closed the window.

Moreover, we can use wildcard in the event name to handle all expired events of multiple times in one time:

```hvml
    <define as myFooTimerHandler >
        ...
   </define>

    <observe on $TIMERS for 'expired:foo*' with $myFooTimerHandler />
```
