### ISSUE TITLE
build failed on mac os monterey(12.3.1 (21E258)) m1 chip

### ISSUE THREAD

**Issue by devbian** [HVML/PurC#3]
## gcc version:
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

## cmake version:
cmake version 3.23.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

## build command:
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPORT=Mac -B build && cmake --build build && sudo cmake --install build 

## error message
[ 73%] Building C object Source/PurC/CMakeFiles/PurC.dir/utils/rbtree.c.o
[ 74%] Building C object Source/PurC/CMakeFiles/PurC.dir/utils/real.c.o
/workspace/PurC/Source/PurC/utils/real.c:775:1: error: '_dummy_f128' declared as an array with a negative size
_COMPILE_TIME_ASSERT(f128, sizeof(long double) == sizeof(uint64_t) * 2);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/workspace/PurC/Source/PurC/utils/real.c:774:36: note: expanded from macro '_COMPILE_TIME_ASSERT'
       typedef int _dummy_ ## name[(x) * 2 - 1]
                                   ^~~~~~~~~~~
1 error generated.
make[2]: *** [Source/PurC/CMakeFiles/PurC.dir/utils/real.c.o] Error 1
make[1]: *** [Source/PurC/CMakeFiles/PurC.dir/all] Error 2
make: *** [all] Error 2

**Comment by VincentWei** [comment]
The error means that the long double on your platform is not 128 bits...

Let's see how to suppress this error.

Thanks for your report!

**Comment by VincentWei** [comment]
Fixed. Please pull and try again.

**Comment by devbian** [comment]
@VincentWei Greate. 
compile success.

![image](https://user-images.githubusercontent.com/620615/182334307-59aa03ac-9951-4f7d-8640-0aa67b33d1ef.png)
