### ISSUE TITLE
purc no found shared library

### ISSUE THREAD

**Issue by MinuxL** [HVML/PurC#30]
> 安装方式

```sh
# git clone purc
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPORT=Linux -B build && cmake --build build && sudo cmake --install build
```

> 执行
```sh
purc
```

```text
purc: error while loading shared libraries: libpurc.so.0: cannot open shared object file: No such file or directory
```

```sh
ldd /usr/local/bin/purc
```

```text
	linux-vdso.so.1 (0x00007fffce0ff000)
	libpurc.so.0 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a7de08000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2a7e05d000)
```

```sh
ls -l /usr/local/lib/libpurc*
```

```text
lrwxrwxrwx 1 root root       12  9月 26 22:26 /usr/local/lib/libpurc.so -> libpurc.so.0
lrwxrwxrwx 1 root root       16  9月 26 22:26 /usr/local/lib/libpurc.so.0 -> libpurc.so.0.8.2
-rw-r--r-- 1 root root 35127256  9月 26 22:22 /usr/local/lib/libpurc.so.0.8.2
```

> 这可执行文件正常 不过动态库是指向编译目录下的

```sh
./build/Source/Executables/purc/purc  --version    # purc 0.8.2
```

不知道哪里影响最终的可执行文件

**Comment by VincentWei** [comment]
在 README.md 文件中有这样一句话：

> Make sure that you have added /usr/local/lib to /etc/ld.so.conf and run sudo ldconfig command, in order that the system can find the shared library of PurC you just installed into /usr/local/lib.

意思是，如果安装一个新的共享库到 `/usr/local/lib` 目录下，需要运行 `sudo ldconfig` 命令，否则在运行时找不到这个库。这个命令用于刷新共享库名称的缓存。

**Comment by MinuxL** [comment]
> 在 README.md 文件中有这样一句话：
> 
> > Make sure that you have added /usr/local/lib to /etc/ld.so.conf and run sudo ldconfig command, in order that the system can find the shared library of PurC you just installed into /usr/local/lib.
> 
> 意思是，如果安装一个新的共享库到 `/usr/local/lib` 目录下，需要运行 `sudo ldconfig` 命令，否则在运行时找不到这个库。这个命令用于刷新共享库名称的缓存。

谢了, 没看全文档.
