### ISSUE TITLE
The output is different while running readme`s demo on ubuntu22.04, x86_64

### ISSUE THREAD

**Issue by GooTal** [HVML/PurC#37]
Hi, i installed purc using this command:
```
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPORT=Linux -B build && cmake --build build && sudo cmake --install build
```
And did as readme said:
![图片](https://user-images.githubusercontent.com/40800103/201459652-7ff0ca76-7d03-4d48-866b-55c011f134dd.png)
But i got no more message but this: 
![图片](https://user-images.githubusercontent.com/40800103/201459848-95116d7b-8d48-4106-804c-1af3da64b46b.png)

Additionally, i try to run hello world demo as readme described:
![图片](https://user-images.githubusercontent.com/40800103/201459790-e68cd112-aea3-4208-ac79-7ba0fa601b81.png)
But i got two message printing:
![图片](https://user-images.githubusercontent.com/40800103/201459840-8c81ee37-155f-4089-91e4-fb87bd4a432f.png)

Is there something i missed?

**Comment by VincentWei** [comment]
Sorry that there is a bug in this version.

For a workaround, you can use `-b` for the verbose output:

```
$ purc -b error.hvml
```

We will fix this bug in Version 0.9.2, which will be released in the near future.

**Comment by GooTal** [comment]
I pulled the master branch, and it seems that `-b` option is not support anymore. 
![图片](https://user-images.githubusercontent.com/40800103/201591779-e7b9e67d-0ed3-400b-9298-1dc542e246a6.png)
I used `-h` option and got that `-v` is for verbose output. But still got no more verbose output.
![图片](https://user-images.githubusercontent.com/40800103/201592118-39bc714e-65ad-4439-9c70-82e9c5b387b9.png)

**Comment by VincentWei** [comment]
Edit this file:

https://github.com/HVML/PurC/blob/master/Source/Executables/purc/purc.c

Change Line 420 to

```c
case 'V':
```

Change Line 485 to 

```c
case 'v':
```

Hope this can help you.

**Comment by GooTal** [comment]
Thanks a lot!
Hoping a better version in the near future :).
真心希望hvml变强变好！

**Comment by VincentWei** [comment]
Many thanks for your encouragement!

**Comment by VincentWei** [comment]
We just pushed the latest code to this repo. The bug mentioned in this issue has been fixed.

Thanks for your patience!
