### ISSUE TITLE
License GPLv3 or LGPLv3

### ISSUE THREAD

**Issue by bkmgit** [HVML/PurC#39]
The file https://github.com/HVML/PurC/blob/master/COPYING.LESSER indicates PurC is available under LGPLv3,
but many files indicate GPLv3:
https://github.com/HVML/PurC/blob/master/Source/Executables/purc/purc.c
https://github.com/HVML/PurC/blob/master/Source/Tools/debian/copyright
https://github.com/HVML/PurC/blob/master/README.md

My understanding is that correct license is GPL, but if the included files from miniGUI have been relicensed under LGPL,
LGPL seems fine.

Can make a pull request to update the code either way.

**Comment by VincentWei** [comment]
This repo contains multiple software components licensed under different licenses.

The main component, the library PurC, is licensed under LGPL. However, `purc` is an executable program uses the PurC library, so it is licensed under GPL.

**Comment by VincentWei** [comment]
This repo contains multiple software components licensed under different licenses.

The main component, the library PurC, is licensed under LGPL. However, `purc` is an executable program uses the PurC library, so it is licensed under GPL.

**Comment by VincentWei** [comment]
This repo contains multiple software components licensed under different licenses.

The main component, the library PurC, is licensed under LGPL. However, `purc` under `Source/Executables` is a command line program. It is not a library. It is an executable program uses the PurC library, so it is licensed under GPL.

**Comment by bkmgit** [comment]
谢谢
