### ISSUE TITLE
Calculator Crash without bc which is used for command line calculator on Linux

### ISSUE THREAD

**Issue by longlongvip** [HVML/PurC#42]
## Aren't you using Linux, why is there no bc command?
I use Arch Linux, and I don't install bc, you can install bc by typing `sudo pacman -s bc` on Arch Linux
## Calculator should not crash
Calculator should not crash even without bc and some tips should be given
## Calculator works
Calculator works after I installed bc
```bash
sudo pacman -s bc
```

**Comment by VincentWei** [comment]
Thanks for your report!

**Comment by VincentWei** [comment]
Fixed in version 0.9.4.
