### ISSUE TITLE
使用ziglang包管理工具构建PurC?

### ISSUE THREAD

**Issue by Chanyon** [HVML/PurC#53]
ziglang构建ffmpeg:`https://github.com/andrewrk/ffmpeg`

**Comment by VincentWei** [comment]
使用这个 ziglang 包管理工具具体能得到什么样的好处呢？能否说说。

**Comment by Chanyon** [comment]
> 使用这个 ziglang 包管理工具具体能得到什么样的好处呢？能否说说。

1.支持交叉编译，
2.让构建编译c项目方式轻松一点。
