### ISSUE TITLE
build failed in Debian 11, gcc version 10.2.1 20210110 (Debian 10.2.1-6)

### ISSUE THREAD

**Issue by atzlinux** [HVML/PurC#7]
cmake version 3.18.4
GLIBC 2.33-8
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

`[ 67%] Building C object Source/PurC/CMakeFiles/PurC.dir/instance/move-buffer.c.o
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c: In function ‘do_move_message’:
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:334:30: error: array subscript 5 is outside the bounds of an interior zero-length array ‘struct purc_variant *[0]’ {aka ‘struct purc_variant *[]’} [-Werror=zero-length-bounds]
  334 |             if (msg->variants[i])
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:28:
/home/atzlinux/devel/HVML-PurC/Source/PurC/include/purc-pcrdr.h:680:21: note: while referencing ‘variants’
  680 |     purc_variant_t  variants[0];
      |                     ^~~~~~~~
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:335:30: error: array subscript 5 is outside the bounds of an interior zero-length array ‘struct purc_variant *[0]’ {aka ‘struct purc_variant *[]’} [-Werror=zero-length-bounds]
  335 |                 msg->variants[i] = pcvariant_move_heap_in(msg->variants[i]);
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:28:
/home/atzlinux/devel/HVML-PurC/Source/PurC/include/purc-pcrdr.h:680:21: note: while referencing ‘variants’
  680 |     purc_variant_t  variants[0];
      |                     ^~~~~~~~
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c: In function ‘pcinst_put_message’:
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:167:30: error: array subscript 5 is outside the bounds of an interior zero-length array ‘struct purc_variant *[0]’ {aka ‘struct purc_variant *[]’} [-Werror=zero-length-bounds]
  167 |             if (msg->variants[i])
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:28:
/home/atzlinux/devel/HVML-PurC/Source/PurC/include/purc-pcrdr.h:680:21: note: while referencing ‘variants’
  680 |     purc_variant_t  variants[0];
      |                     ^~~~~~~~
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c: In function ‘purc_inst_destroy_move_buffer’:
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:257:30: error: array subscript 5 is outside the bounds of an interior zero-length array ‘struct purc_variant *[0]’ {aka ‘struct purc_variant *[]’} [-Werror=zero-length-bounds]
  257 |             if (msg->variants[i])
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:28:
/home/atzlinux/devel/HVML-PurC/Source/PurC/include/purc-pcrdr.h:680:21: note: while referencing ‘variants’
  680 |     purc_variant_t  variants[0];
      |                     ^~~~~~~~
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c: In function ‘purc_inst_take_away_message’:
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:352:30: error: array subscript 5 is outside the bounds of an interior zero-length array ‘struct purc_variant *[0]’ {aka ‘struct purc_variant *[]’} [-Werror=zero-length-bounds]
  352 |             if (msg->variants[i])
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:28:
/home/atzlinux/devel/HVML-PurC/Source/PurC/include/purc-pcrdr.h:680:21: note: while referencing ‘variants’
  680 |     purc_variant_t  variants[0];
      |                     ^~~~~~~~
/home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:353:30: error: array subscript 5 is outside the bounds of an interior zero-length array ‘struct purc_variant *[0]’ {aka ‘struct purc_variant *[]’} [-Werror=zero-length-bounds]
  353 |                 msg->variants[i] = pcvariant_move_heap_out(msg->variants[i]);
      |                 ~~~~~~~~~~~~~^~~
In file included from /home/atzlinux/devel/HVML-PurC/Source/PurC/instance/move-buffer.c:28:
/home/atzlinux/devel/HVML-PurC/Source/PurC/include/purc-pcrdr.h:680:21: note: while referencing ‘variants’
  680 |     purc_variant_t  variants[0];
      |                     ^~~~~~~~
cc1: all warnings being treated as errors
gmake[2]: *** [Source/PurC/CMakeFiles/PurC.dir/build.make:3537：Source/PurC/CMakeFiles/PurC.dir/instance/move-buffer.c.o] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:1093：Source/PurC/CMakeFiles/PurC.dir/all] 错误 2
gmake: *** [Makefile:171：all] 错误 2
`

**Comment by VincentWei** [comment]
Thanks for you report!
This compilation error (a warning in deed) has been fixed.
Please try again.
